In [5]:
a=20
b=10
c=a+b
c

30

In [7]:
a=10
b=20
print(a)
b

10


20

In [40]:
set=[13,45,67,81,34]
set

[13, 45, 67, 81, 34]

In [41]:
import numpy as np
value=np.array(set)
value

array([13, 45, 67, 81, 34])

In [42]:
c=np.mean(value)
c

np.float64(48.0)

In [43]:
print(max(value))

81


In [44]:
print(min(value))

13


In [19]:
d=np.zeros([3,5])
d

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
d=np.ones([3,5])
d

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
c=np.random.rand(5,3)
c

array([[0.07510261, 0.47125218, 0.73552007],
       [0.29828337, 0.6822205 , 0.11354548],
       [0.58489453, 0.20344353, 0.47930575],
       [0.79531906, 0.52941592, 0.85961666],
       [0.11508513, 0.65794673, 0.84965053]])

In [24]:
a=np.array([1,3,4,5,6,7,8,9,10,12,11,13,14,15,16,17,18,19])
b=np.reshape(a,(2,9))
b

array([[ 1,  3,  4,  5,  6,  7,  8,  9, 10],
       [12, 11, 13, 14, 15, 16, 17, 18, 19]])

In [33]:
c=np.arange(20).reshape(4,5)
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [48]:
f=([11,34,56,78,9,0,12,4,5,6,7,8])
d=f[2:7]
d

[56, 78, 9, 0, 12]

In [50]:
a=np.array([2,4,6])
b=np.array([3,5,1])
a+b

array([5, 9, 7])

In [51]:
a=np.array([5,9,6])
b=np.array([3,5,1])
a-b

array([2, 4, 5])

In [52]:
a=np.array([5,9,6])
b=np.array([3,5,2])
a*b

array([15, 45, 12])

In [54]:
a=np.array([2,4,6]),([3,2,1])
b=np.array([6,5]),([4,2]),([3,2])
c=np.dot(a,b)
c

array([[46, 30],
       [29, 21]])

In [60]:
find = np.array([[1,3,5,6],[3,7,8,9]])
print(find.T)

[[1 3]
 [3 7]
 [5 8]
 [6 9]]


In [61]:
value=[9,7,4,5,1,0,2,6]
print(np.sort(value))


[0 1 2 4 5 6 7 9]


In [66]:
a=np.array([4,5,6])
b=np.array([1,2,3])
print(np.concatenate((b,a)))

[1 2 3 4 5 6]


In [67]:
a=[1,1,4,6,7,9,2,2]
d=np.unique(a)
d

array([1, 2, 4, 6, 7, 9])

In [70]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [72]:
set=np.linspace(11,20,5)
print(set)

[11.   13.25 15.5  17.75 20.  ]
